name: windows-mingw-stress

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'CMakeLists.txt'
      - '.github/workflows/windows-mingw-stress.yml'
  pull_request:
    branches: [ main ]

jobs:
  build-and-stress:
    runs-on: windows-latest
    timeout-minutes: 60
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2 MinGW64
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            base-devel
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja

      - name: Configure
        run: >-
          cmake -S . -B build/mingw64-Release -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DIO_BUILD_TESTS=ON
          -DIO_BUILD_EXAMPLES=OFF

      - name: Build
        run: cmake --build build/mingw64-Release -j 4

      - name: Stress (IOCP write path)
        env:
          IO_STRESS_N: '32'
          IO_STRESS_REPEATS: '200'
          IO_STRESS_PAYLOAD: '32768'
        run: >-
          ctest --test-dir build/mingw64-Release -R WinIocp.HighloadLargePayload
          --output-on-failure --repeat until-fail:20 --timeout 900

      - name: Stress (server write flood)
        env:
          IO_STRESS_N: '24'
          IO_STRESS_REPEATS: '120'
          IO_STRESS_PAYLOAD: '32768'
        run: >-
          ctest --test-dir build/mingw64-Release -R WinIocp.WriteFloodServerToClients
          --output-on-failure --repeat until-fail:10 --timeout 900

      - name: Stress (accept autotune)
        env:
          IO_STRESS_N: '64'
        run: >-
          ctest --test-dir build/mingw64-Release -R WinIocp.AcceptAutotunePressure
          --output-on-failure --repeat until-fail:5 --timeout 600
